name: phys139
channels:
    - pyg
    - pytorch
    - conda-forge
dependencies:
    - python=3.9
    - numpy
    - uproot
    - tensorflow
    - xrootd
    - scikit-learn
    - matplotlib
    - pytorch
    - torchvision
    - torchaudio
    - cpuonly
    - pyg
    - mplhep
    - tqdm
    - xgboost
    - pip
    - pip:
      - jupyter-book
      - jetnet
      - gdown
      - spektral
      - zenodo_get
      - requests
      - ipywidgets
      - widgetsnbextension
      - jupyter_contrib_nbextensions
